package com.application.ncg.cityvendorappsuite.providers;

import android.database.sqlite.SQLiteDatabase;

/**
 * This is a utility class for Vendors Content Provider
 * Created by Chris on 2015-03-07.
 */
public class VendorsTable{

    public static final String VENDORS_TABLE_NAME = "vendors";
    public static final String COLUMN_NAME = "name";
    public static final String COLUMN_VENDOR_ID = "vendorID"; //This is the global ID
    public static final String COLUMN_CP_VENDOR_ID = "_ID"; //this is 'local' ID generated by CP
    public static final String COLUMN_PRODUCT_ID = "productsID";
    public static final String COLUMN_SURNAME ="surname";
    public static final String COLUMN_EMAIL ="email";
    public static final String COLUMN_LATITUDE="latitude";
    public static final String COLUMN_LONGITUDE ="longitude";
    public static final String COLUMN_STREET_ADDRESS="streetAddress";

    public static final String DEFAULT_SORT_ORDER = "_ID Desc";

    public static final String[] DEFAULT_VENDORS_PROJECTIONS = {COLUMN_NAME,COLUMN_STREET_ADDRESS,
                                                        COLUMN_VENDOR_ID,COLUMN_LONGITUDE,
                                                        COLUMN_PRODUCT_ID,COLUMN_LATITUDE,
                                                        COLUMN_SURNAME,COLUMN_EMAIL};

    private static final String CREATE_TABLE_QUERY = " CREATE TABLE "+VENDORS_TABLE_NAME+" "
            +" ( "+COLUMN_CP_VENDOR_ID+" integer primary key autoincrement,"
            +COLUMN_VENDOR_ID+ " text, "
            +COLUMN_NAME+ " text not null, "
            +COLUMN_SURNAME+ " text not null, "
            +COLUMN_EMAIL+ " text not null, "
            +COLUMN_LATITUDE+" text not null, "
            +COLUMN_LONGITUDE+" text not null, "
            +COLUMN_STREET_ADDRESS+" text not null)";
    private static final String DROP_TABLE_QUERY = "DROP TABLE IF EXISTS "+VENDORS_TABLE_NAME;

    public static void onCreate(SQLiteDatabase database){
        //create a database/table
        database.execSQL(CREATE_TABLE_QUERY);
    }

    public static void onUpgrade(SQLiteDatabase database){
        //update the database/table
        database.execSQL(DROP_TABLE_QUERY);
        onCreate(database);
    }

}
